/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF, PerspectiveCamera } from "@react-three/drei";

export function LaundromatModel(props) {
  const { nodes, materials } = useGLTF("models/Laundromat_21_ad.glb");
  return (
    <group {...props} dispose={null}>
      <PerspectiveCamera
        name="Camera"
        makeDefault={false}
        far={1000}
        near={0.1}
        fov={26.3786}
        position={[-1.7996, 2.092, 7.209]}
        rotation={[0.0925, -0.2937, 0.0164]}
        scale={0.502}
      />
      <group
        name="Washing_Machines"
        position={[-2.0146, 2.4622, 0.1467]}
        rotation={[0, 0.0123, 0]}
      >
        <mesh
          name="Cube004"
          castShadow
          receiveShadow
          geometry={nodes.Cube004.geometry}
          material={materials["Washing Machines"]}
        />
        <mesh
          name="Cube004_1"
          castShadow
          receiveShadow
          geometry={nodes.Cube004_1.geometry}
          material={materials["Washing Machine Interior"]}
        />
        <mesh
          name="Cube004_2"
          castShadow
          receiveShadow
          geometry={nodes.Cube004_2.geometry}
          material={materials["Washing Machines.001"]}
        />
      </group>
      <mesh
        name="Gumball_Machine"
        castShadow
        receiveShadow
        geometry={nodes.Gumball_Machine.geometry}
        material={materials["Gumball Machine"]}
        position={[1.3325, 2.6917, -0.163]}
      />
      <mesh
        name="Clothes_Basket"
        castShadow
        receiveShadow
        geometry={nodes.Clothes_Basket.geometry}
        material={materials["Clothes Basket"]}
        position={[0.0284, 3.2429, 0.2699]}
        rotation={[-0.0323, 0.4546, 0]}
      >
        <mesh
          name="Clothes"
          castShadow
          receiveShadow
          geometry={nodes.Clothes.geometry}
          material={materials["Blank Difuse Material"]}
          position={[-0.0979, 0.0884, 0.0362]}
          rotation={[0, -0.4546, 0]}
          scale={0.3146}
        />
      </mesh>
      <mesh
        name="Soap_Bottle"
        castShadow
        receiveShadow
        geometry={nodes.Soap_Bottle.geometry}
        material={materials["Material.002"]}
        position={[0.6608, 3.2261, 0.254]}
        rotation={[0, 0.0899, -0.0041]}
      />
      <group name="Coffee_Cup" position={[0.5486, 3.0626, 0.2736]}>
        <mesh
          name="Cylinder"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder.geometry}
          material={materials.Coffeecup}
        />
        <mesh
          name="Cylinder_1"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_1.geometry}
          material={materials.Coffeecup_Label}
        />
      </group>
      <group
        name="Chair_1"
        position={[2.4908, 2.4505, 1.1555]}
        rotation={[0, 0.0826, 0]}
      >
        <mesh
          name="Cube002"
          castShadow
          receiveShadow
          geometry={nodes.Cube002.geometry}
          material={materials.Chair}
        />
        <mesh
          name="Cube002_1"
          castShadow
          receiveShadow
          geometry={nodes.Cube002_1.geometry}
          material={materials["Chair Legs"]}
        />
      </group>
      <group
        name="Clock"
        position={[-0.6308, 3.9752, -0.496]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.0618}
      >
        <mesh
          name="Cylinder002_1"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder002_1.geometry}
          material={materials["Clock Border"]}
        />
        <mesh
          name="Cylinder002_2"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder002_2.geometry}
          material={materials["Clock BG"]}
        />
        <mesh
          name="Cylinder001"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001.geometry}
          material={materials["Clock Hands"]}
          position={[0, -0.0018, 0]}
          rotation={[Math.PI, -0.437, Math.PI]}
        >
          <mesh
            name="Cylinder003"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder003.geometry}
            material={materials["Clock Hands"]}
            position={[0, -0.002, 0]}
            rotation={[-Math.PI, 0.2259, -Math.PI]}
            scale={1.4034}
          >
            <mesh
              name="Cylinder002"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder002.geometry}
              material={materials["Clock Hands"]}
              rotation={[Math.PI, -0.5862, Math.PI]}
              scale={0.7334}
            />
          </mesh>
        </mesh>
      </group>
      <mesh
        name="Poster"
        castShadow
        receiveShadow
        geometry={nodes.Poster.geometry}
        material={materials.Posters}
        position={[1.2813, 4.3, -0.5009]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Poster001"
        castShadow
        receiveShadow
        geometry={nodes.Poster001.geometry}
        material={materials.Posters}
        position={[0.7691, 4.475, -0.4983]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Poster002"
        castShadow
        receiveShadow
        geometry={nodes.Poster002.geometry}
        material={materials.Posters}
        position={[-2.2539, 3.9686, 4.1622]}
        rotation={[Math.PI / 2, 0, -1.6222]}
        scale={1.801}
      />
      <mesh
        name="Plant"
        castShadow
        receiveShadow
        geometry={nodes.Plant.geometry}
        material={materials.Plant}
        position={[-1.9397, 3.2515, 0]}
      />
      <mesh
        name="Fan"
        castShadow
        receiveShadow
        geometry={nodes.Fan.geometry}
        material={materials.Fan}
        position={[-1.3484, 3.0909, -0.0318]}
      />
      <group
        name="Chair_1001"
        position={[2.0346, 2.4505, 0.5238]}
        rotation={[0, 0.3009, 0]}
      >
        <mesh
          name="Cube015"
          castShadow
          receiveShadow
          geometry={nodes.Cube015.geometry}
          material={materials.Chair}
        />
        <mesh
          name="Cube015_1"
          castShadow
          receiveShadow
          geometry={nodes.Cube015_1.geometry}
          material={materials["Chair Legs"]}
        />
      </group>
      <mesh
        name="Poster003"
        castShadow
        receiveShadow
        geometry={nodes.Poster003.geometry}
        material={materials.Posters}
        position={[3.4786, 4.7633, 0.8272]}
        rotation={[Math.PI / 2, 0, 0.9473]}
      />
      <mesh
        name="Poster004"
        castShadow
        receiveShadow
        geometry={nodes.Poster004.geometry}
        material={materials.Posters}
        position={[2.9199, 4.0329, 0.029]}
        rotation={[Math.PI / 2, 0, 0.9473]}
      />
      <group
        name="Torus001"
        position={[-0.0968, 2.4833, 0.608]}
        rotation={[Math.PI / 2, 0, -0.1885]}
      >
        <mesh
          name="Torus001_1"
          castShadow
          receiveShadow
          geometry={nodes.Torus001_1.geometry}
          material={materials["Machine Lid"]}
        />
        <mesh
          name="Torus001_2"
          castShadow
          receiveShadow
          geometry={nodes.Torus001_2.geometry}
          material={materials.Glass}
        />
      </group>
      <group
        name="Torus002"
        position={[0.6664, 2.4799, 0.608]}
        rotation={[Math.PI / 2, 0, -0.7685]}
      >
        <mesh
          name="Torus007"
          castShadow
          receiveShadow
          geometry={nodes.Torus007.geometry}
          material={materials["Machine Lid"]}
        />
        <mesh
          name="Torus007_1"
          castShadow
          receiveShadow
          geometry={nodes.Torus007_1.geometry}
          material={materials.Glass}
        />
      </group>
      <group
        name="Torus003"
        position={[-0.9551, 2.4883, 0.608]}
        rotation={[Math.PI / 2, 0, -0.7726]}
      >
        <mesh
          name="Torus008"
          castShadow
          receiveShadow
          geometry={nodes.Torus008.geometry}
          material={materials["Machine Lid"]}
        />
        <mesh
          name="Torus008_1"
          castShadow
          receiveShadow
          geometry={nodes.Torus008_1.geometry}
          material={materials.Glass}
        />
      </group>
      <group
        name="Torus004"
        position={[-1.7924, 2.4939, 0.608]}
        rotation={[Math.PI / 2, 0, -0.0065]}
      >
        <mesh
          name="Torus009"
          castShadow
          receiveShadow
          geometry={nodes.Torus009.geometry}
          material={materials["Machine Lid"]}
        />
        <mesh
          name="Torus009_1"
          castShadow
          receiveShadow
          geometry={nodes.Torus009_1.geometry}
          material={materials.Glass}
        />
      </group>
      <mesh
        name="Fan_Back"
        castShadow
        receiveShadow
        geometry={nodes.Fan_Back.geometry}
        material={materials.Fan}
        position={[-1.3771, 3.4506, -0.0341]}
        rotation={[0, -0.7458, 0]}
      >
        <mesh
          name="Fan_Front"
          castShadow
          receiveShadow
          geometry={nodes.Fan_Front.geometry}
          material={materials.Fan}
          position={[2.3664, -2.9056, 0.0341]}
          rotation={[0, 0, 0.2923]}
        >
          <mesh
            name="Fan_Cage"
            castShadow
            receiveShadow
            geometry={nodes.Fan_Cage.geometry}
            material={materials["Fan Cage"]}
            position={[-1.2706, 3.4698, -0.0332]}
            rotation={[0, 0, -0.2923]}
          />
        </mesh>
      </mesh>
      <mesh
        name="Sky"
        castShadow
        receiveShadow
        geometry={nodes.Sky.geometry}
        material={materials["Material.001"]}
        position={[13.1803, 0, -15.7017]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        name="BG_Building"
        castShadow
        receiveShadow
        geometry={nodes.BG_Building.geometry}
        material={materials["BG Building"]}
        position={[6.9488, 3.4067, -11.5945]}
      />
      <mesh
        name="BG_Building001"
        castShadow
        receiveShadow
        geometry={nodes.BG_Building001.geometry}
        material={materials["BG Building"]}
        position={[13.0216, 2.4079, -12.7939]}
      />
      <mesh
        name="Plane003"
        castShadow
        receiveShadow
        geometry={nodes.Plane003.geometry}
        material={materials.Building}
      />
      <mesh
        name="Plane003_1"
        castShadow
        receiveShadow
        geometry={nodes.Plane003_1.geometry}
        material={materials["Floor Tiles - Dark"]}
      />
      <mesh
        name="Plane003_2"
        castShadow
        receiveShadow
        geometry={nodes.Plane003_2.geometry}
        material={materials["Floor Tiles - Light"]}
      />
      <mesh
        name="Plane003_3"
        castShadow
        receiveShadow
        geometry={nodes.Plane003_3.geometry}
        material={materials["Building - Light Accents"]}
      />
    </group>
  );
}

useGLTF.preload("/Laundromat_21_ad.glb");
